name       : glpk
version    : '5.0'
release    : 3
source     :
    - https://ftp.gnu.org/gnu/glpk/glpk-5.0.tar.gz : 4a1013eebb50f728fc601bdd833b0b2870333c3b3e5a816eeba921d95bec6f15
license    : GPL-3.0-or-later
component  : programming
summary    : The GLPK (GNU Linear Programming Kit) package
description: |
    The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems. It is a set of routines written in ANSI C and organized in the form of a callable library.
optimize   : speed
setup      : |
    %configure --disable-static \
        --with-gmp
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
