name       : glpk
version    : '4.65'
release    : 2
source     :
    - https://ftp.gnu.org/gnu/glpk/glpk-4.65.tar.gz : 4281e29b628864dfe48d393a7bedd781e5b475387c20d8b0158f329994721a10
license    : GPL-3.0-or-later
component  : programming
summary    : The GLPK (GNU Linear Programming Kit) package
description: |
    The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems. It is a set of routines written in ANSI C and organized in the form of a callable library.
optimize   : speed
setup      : |
    %configure --prefix=/usr \
        --disable-static \
        --with-gmp \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check