name       : glpk
version    : 4.60
release    : 1
source     :
    - http://ftp.gnu.org/gnu/glpk/glpk-4.60.tar.gz : 1356620cb0a0d33ac3411dd49d9fd40d53ece73eaec8f6b8d19a77887ff5e297
license    : GPL-3.0
component  : programming
summary    : The GLPK (GNU Linear Programming Kit) package
description: |
    The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems. It is a set of routines written in ANSI C and organized in the form of a callable library.
optimize: speed
setup      : |
    %configure --prefix=/usr \
        --disable-static \
        --with-gmp \
        --with-zlib
build      : |
    %make
install    : |
    %make_install
